[2024-04-17T10:09:51.546-0300] {processor.py:161} INFO - Started process (PID=22774) to work on /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-17T10:09:51.547-0300] {processor.py:830} INFO - Processing file /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-17T10:09:51.549-0300] {logging_mixin.py:188} INFO - [2024-04-17T10:09:51.548-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-17T10:09:51.552-0300] {logging_mixin.py:188} INFO - [2024-04-17T10:09:51.551-0300] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-17T10:09:51.552-0300] {logging_mixin.py:188} INFO - [2024-04-17T10:09:51.552-0300] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-17T10:09:51.552-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-17T10:09:51.560-0300] {processor.py:183} INFO - Processing /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2024-04-17T10:10:48.346-0300] {processor.py:161} INFO - Started process (PID=23383) to work on /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-17T10:10:48.348-0300] {processor.py:830} INFO - Processing file /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-17T10:10:48.349-0300] {logging_mixin.py:188} INFO - [2024-04-17T10:10:48.349-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-17T10:10:48.351-0300] {logging_mixin.py:188} INFO - [2024-04-17T10:10:48.351-0300] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-17T10:10:48.352-0300] {logging_mixin.py:188} INFO - [2024-04-17T10:10:48.352-0300] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-17T10:10:48.352-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-17T10:10:48.359-0300] {processor.py:183} INFO - Processing /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2024-04-17T10:11:31.728-0300] {processor.py:161} INFO - Started process (PID=23729) to work on /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-17T10:11:31.734-0300] {processor.py:830} INFO - Processing file /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-17T10:11:31.736-0300] {logging_mixin.py:188} INFO - [2024-04-17T10:11:31.736-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-17T10:11:31.741-0300] {logging_mixin.py:188} INFO - [2024-04-17T10:11:31.739-0300] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-17T10:11:31.741-0300] {logging_mixin.py:188} INFO - [2024-04-17T10:11:31.741-0300] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-17T10:11:31.742-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-17T10:11:31.750-0300] {processor.py:183} INFO - Processing /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2024-04-17T10:12:11.653-0300] {processor.py:161} INFO - Started process (PID=24114) to work on /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-17T10:12:11.659-0300] {processor.py:830} INFO - Processing file /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-17T10:12:11.661-0300] {logging_mixin.py:188} INFO - [2024-04-17T10:12:11.661-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-17T10:12:11.663-0300] {logging_mixin.py:188} INFO - [2024-04-17T10:12:11.663-0300] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-17T10:12:11.664-0300] {logging_mixin.py:188} INFO - [2024-04-17T10:12:11.664-0300] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-17T10:12:11.664-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-17T10:12:11.672-0300] {processor.py:183} INFO - Processing /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2024-04-17T10:13:05.088-0300] {processor.py:161} INFO - Started process (PID=24992) to work on /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-17T10:13:05.097-0300] {processor.py:830} INFO - Processing file /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-17T10:13:05.102-0300] {logging_mixin.py:188} INFO - [2024-04-17T10:13:05.101-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-17T10:13:05.116-0300] {logging_mixin.py:188} INFO - [2024-04-17T10:13:05.109-0300] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-17T10:13:05.117-0300] {logging_mixin.py:188} INFO - [2024-04-17T10:13:05.117-0300] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-17T10:13:05.118-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-17T10:13:05.158-0300] {processor.py:183} INFO - Processing /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.091 seconds
[2024-04-17T10:13:47.482-0300] {processor.py:161} INFO - Started process (PID=25550) to work on /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-17T10:13:47.489-0300] {processor.py:830} INFO - Processing file /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-17T10:13:47.490-0300] {logging_mixin.py:188} INFO - [2024-04-17T10:13:47.490-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-17T10:13:47.493-0300] {logging_mixin.py:188} INFO - [2024-04-17T10:13:47.492-0300] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-17T10:13:47.493-0300] {logging_mixin.py:188} INFO - [2024-04-17T10:13:47.493-0300] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-17T10:13:47.493-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-17T10:13:47.500-0300] {processor.py:183} INFO - Processing /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2024-04-17T10:14:24.032-0300] {processor.py:161} INFO - Started process (PID=25999) to work on /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-17T10:14:24.033-0300] {processor.py:830} INFO - Processing file /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-17T10:14:24.035-0300] {logging_mixin.py:188} INFO - [2024-04-17T10:14:24.034-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-17T10:14:24.038-0300] {logging_mixin.py:188} INFO - [2024-04-17T10:14:24.038-0300] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-17T10:14:24.038-0300] {logging_mixin.py:188} INFO - [2024-04-17T10:14:24.038-0300] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-17T10:14:24.038-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-17T10:14:24.046-0300] {processor.py:183} INFO - Processing /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2024-04-17T10:15:02.991-0300] {processor.py:161} INFO - Started process (PID=26368) to work on /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-17T10:15:02.997-0300] {processor.py:830} INFO - Processing file /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-17T10:15:02.998-0300] {logging_mixin.py:188} INFO - [2024-04-17T10:15:02.998-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-17T10:15:03.000-0300] {logging_mixin.py:188} INFO - [2024-04-17T10:15:03.000-0300] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-17T10:15:03.000-0300] {logging_mixin.py:188} INFO - [2024-04-17T10:15:03.000-0300] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-17T10:15:03.001-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-17T10:15:03.007-0300] {processor.py:183} INFO - Processing /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2024-04-17T10:15:44.897-0300] {processor.py:161} INFO - Started process (PID=26791) to work on /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-17T10:15:44.898-0300] {processor.py:830} INFO - Processing file /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-17T10:15:44.900-0300] {logging_mixin.py:188} INFO - [2024-04-17T10:15:44.899-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-17T10:15:44.902-0300] {logging_mixin.py:188} INFO - [2024-04-17T10:15:44.901-0300] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-17T10:15:44.902-0300] {logging_mixin.py:188} INFO - [2024-04-17T10:15:44.902-0300] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-17T10:15:44.902-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-17T10:15:44.909-0300] {processor.py:183} INFO - Processing /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2024-04-17T10:16:25.317-0300] {processor.py:161} INFO - Started process (PID=27137) to work on /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-17T10:16:25.319-0300] {processor.py:830} INFO - Processing file /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-17T10:16:25.320-0300] {logging_mixin.py:188} INFO - [2024-04-17T10:16:25.319-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-17T10:16:25.322-0300] {logging_mixin.py:188} INFO - [2024-04-17T10:16:25.321-0300] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-17T10:16:25.322-0300] {logging_mixin.py:188} INFO - [2024-04-17T10:16:25.322-0300] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-17T10:16:25.322-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-17T10:16:25.330-0300] {processor.py:183} INFO - Processing /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2024-04-17T10:17:06.991-0300] {processor.py:161} INFO - Started process (PID=27493) to work on /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-17T10:17:06.997-0300] {processor.py:830} INFO - Processing file /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-17T10:17:06.998-0300] {logging_mixin.py:188} INFO - [2024-04-17T10:17:06.998-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-17T10:17:07.001-0300] {logging_mixin.py:188} INFO - [2024-04-17T10:17:07.000-0300] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-17T10:17:07.001-0300] {logging_mixin.py:188} INFO - [2024-04-17T10:17:07.001-0300] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-17T10:17:07.001-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-17T10:17:07.009-0300] {processor.py:183} INFO - Processing /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2024-04-17T10:17:45.169-0300] {processor.py:161} INFO - Started process (PID=27815) to work on /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-17T10:17:45.176-0300] {processor.py:830} INFO - Processing file /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-17T10:17:45.181-0300] {logging_mixin.py:188} INFO - [2024-04-17T10:17:45.180-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-17T10:17:45.184-0300] {logging_mixin.py:188} INFO - [2024-04-17T10:17:45.184-0300] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-17T10:17:45.185-0300] {logging_mixin.py:188} INFO - [2024-04-17T10:17:45.185-0300] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-17T10:17:45.185-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-17T10:17:45.198-0300] {processor.py:183} INFO - Processing /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2024-04-17T10:18:25.716-0300] {processor.py:161} INFO - Started process (PID=28160) to work on /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-17T10:18:25.718-0300] {processor.py:830} INFO - Processing file /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-17T10:18:25.720-0300] {logging_mixin.py:188} INFO - [2024-04-17T10:18:25.720-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-17T10:18:25.724-0300] {logging_mixin.py:188} INFO - [2024-04-17T10:18:25.723-0300] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-17T10:18:25.724-0300] {logging_mixin.py:188} INFO - [2024-04-17T10:18:25.724-0300] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-17T10:18:25.724-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-17T10:18:25.732-0300] {processor.py:183} INFO - Processing /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2024-04-17T10:19:06.216-0300] {processor.py:161} INFO - Started process (PID=28500) to work on /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-17T10:19:06.218-0300] {processor.py:830} INFO - Processing file /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-17T10:19:06.219-0300] {logging_mixin.py:188} INFO - [2024-04-17T10:19:06.219-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-17T10:19:06.221-0300] {logging_mixin.py:188} INFO - [2024-04-17T10:19:06.221-0300] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-17T10:19:06.222-0300] {logging_mixin.py:188} INFO - [2024-04-17T10:19:06.221-0300] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-17T10:19:06.222-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-17T10:19:06.230-0300] {processor.py:183} INFO - Processing /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2024-04-17T10:19:46.765-0300] {processor.py:161} INFO - Started process (PID=28845) to work on /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-17T10:19:46.767-0300] {processor.py:830} INFO - Processing file /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-17T10:19:46.768-0300] {logging_mixin.py:188} INFO - [2024-04-17T10:19:46.767-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-17T10:19:46.770-0300] {logging_mixin.py:188} INFO - [2024-04-17T10:19:46.769-0300] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-17T10:19:46.770-0300] {logging_mixin.py:188} INFO - [2024-04-17T10:19:46.770-0300] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-17T10:19:46.770-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-17T10:19:46.778-0300] {processor.py:183} INFO - Processing /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2024-04-17T10:20:22.169-0300] {processor.py:161} INFO - Started process (PID=29180) to work on /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-17T10:20:22.171-0300] {processor.py:830} INFO - Processing file /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-17T10:20:22.172-0300] {logging_mixin.py:188} INFO - [2024-04-17T10:20:22.172-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-17T10:20:22.174-0300] {logging_mixin.py:188} INFO - [2024-04-17T10:20:22.173-0300] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-17T10:20:22.174-0300] {logging_mixin.py:188} INFO - [2024-04-17T10:20:22.174-0300] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-17T10:20:22.174-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-17T10:20:22.181-0300] {processor.py:183} INFO - Processing /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2024-04-17T10:21:00.964-0300] {processor.py:161} INFO - Started process (PID=29503) to work on /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-17T10:21:00.966-0300] {processor.py:830} INFO - Processing file /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-17T10:21:00.967-0300] {logging_mixin.py:188} INFO - [2024-04-17T10:21:00.967-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-17T10:21:00.970-0300] {logging_mixin.py:188} INFO - [2024-04-17T10:21:00.969-0300] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-17T10:21:00.970-0300] {logging_mixin.py:188} INFO - [2024-04-17T10:21:00.970-0300] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-17T10:21:00.970-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-17T10:21:00.978-0300] {processor.py:183} INFO - Processing /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2024-04-17T10:21:41.450-0300] {processor.py:161} INFO - Started process (PID=29847) to work on /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-17T10:21:41.456-0300] {processor.py:830} INFO - Processing file /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-17T10:21:41.457-0300] {logging_mixin.py:188} INFO - [2024-04-17T10:21:41.457-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-17T10:21:41.460-0300] {logging_mixin.py:188} INFO - [2024-04-17T10:21:41.459-0300] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-17T10:21:41.460-0300] {logging_mixin.py:188} INFO - [2024-04-17T10:21:41.460-0300] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-17T10:21:41.460-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-17T10:21:41.472-0300] {processor.py:183} INFO - Processing /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2024-04-17T10:22:18.595-0300] {processor.py:161} INFO - Started process (PID=30163) to work on /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-17T10:22:18.600-0300] {processor.py:830} INFO - Processing file /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-17T10:22:18.601-0300] {logging_mixin.py:188} INFO - [2024-04-17T10:22:18.601-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-17T10:22:18.603-0300] {logging_mixin.py:188} INFO - [2024-04-17T10:22:18.603-0300] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-17T10:22:18.603-0300] {logging_mixin.py:188} INFO - [2024-04-17T10:22:18.603-0300] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-17T10:22:18.604-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-17T10:22:18.610-0300] {processor.py:183} INFO - Processing /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2024-04-17T10:22:58.513-0300] {processor.py:161} INFO - Started process (PID=30499) to work on /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-17T10:22:58.520-0300] {processor.py:830} INFO - Processing file /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-17T10:22:58.521-0300] {logging_mixin.py:188} INFO - [2024-04-17T10:22:58.520-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-17T10:22:58.523-0300] {logging_mixin.py:188} INFO - [2024-04-17T10:22:58.523-0300] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-17T10:22:58.523-0300] {logging_mixin.py:188} INFO - [2024-04-17T10:22:58.523-0300] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-17T10:22:58.523-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-17T10:22:58.530-0300] {processor.py:183} INFO - Processing /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2024-04-17T10:23:37.705-0300] {processor.py:161} INFO - Started process (PID=30828) to work on /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-17T10:23:37.706-0300] {processor.py:830} INFO - Processing file /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-17T10:23:37.707-0300] {logging_mixin.py:188} INFO - [2024-04-17T10:23:37.707-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-17T10:23:37.709-0300] {logging_mixin.py:188} INFO - [2024-04-17T10:23:37.709-0300] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-17T10:23:37.709-0300] {logging_mixin.py:188} INFO - [2024-04-17T10:23:37.709-0300] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-17T10:23:37.710-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-17T10:23:37.716-0300] {processor.py:183} INFO - Processing /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2024-04-17T10:24:16.550-0300] {processor.py:161} INFO - Started process (PID=31159) to work on /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-17T10:24:16.552-0300] {processor.py:830} INFO - Processing file /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-17T10:24:16.554-0300] {logging_mixin.py:188} INFO - [2024-04-17T10:24:16.553-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-17T10:24:16.556-0300] {logging_mixin.py:188} INFO - [2024-04-17T10:24:16.555-0300] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-17T10:24:16.556-0300] {logging_mixin.py:188} INFO - [2024-04-17T10:24:16.556-0300] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-17T10:24:16.556-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-17T10:24:16.563-0300] {processor.py:183} INFO - Processing /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2024-04-17T10:24:52.545-0300] {processor.py:161} INFO - Started process (PID=31461) to work on /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-17T10:24:52.547-0300] {processor.py:830} INFO - Processing file /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-17T10:24:52.548-0300] {logging_mixin.py:188} INFO - [2024-04-17T10:24:52.548-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-17T10:24:52.550-0300] {logging_mixin.py:188} INFO - [2024-04-17T10:24:52.550-0300] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-17T10:24:52.550-0300] {logging_mixin.py:188} INFO - [2024-04-17T10:24:52.550-0300] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-17T10:24:52.550-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-17T10:24:52.557-0300] {processor.py:183} INFO - Processing /home/lborba/.cache/pypoetry/virtualenvs/airflow-tutorial-3ROeDTU8-py3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
